version: '3'

services:
  library-eureka:
    image: library-eureka:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "8090:8080"

  book-db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: "book_db"
      POSTGRES_USER: "book_user"
      POSTGRES_PASSWORD: "book_password"
    volumes:
      - book-db-data:/var/lib/postgresql/data

  lib-db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: "lib_db"
      POSTGRES_USER: "lib_user"
      POSTGRES_PASSWORD: "lib_password"
    volumes:
      - lib-db-data:/var/lib/postgresql/data

  library-books:
    image: library-books:0.0.1-SNAPSHOT
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://library-eureka:8080/eureka"
      EUREKA_INSTANCE_INSTANCE_ID: "1"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://book-db:5432/book_db"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_DATASOURCE_USERNAME: "book_user"
      SPRING_DATASOURCE_PASSWORD: "book_password"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"


  library-lib:
    image: library-lib:0.0.1-SNAPSHOT
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://library-eureka:8080/eureka"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://lib-db:5432/lib_db"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_DATASOURCE_USERNAME: "lib_user"
      SPRING_DATASOURCE_PASSWORD: "lib_password"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"


  library-gateway:
    image: library-gateway:0.0.1-SNAPSHOT
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://library-eureka:8080/eureka"
      LIBRARY_GATEWAY_HOST: "library-gateway:8080"

  library-ng:
    image: library-ng:0.0.1-SNAPSHOT
    restart: always
    environment:
      API_URL: http://library-gateway:8080/api
    ports:
      - "8087:80"

volumes:
  book-db-data:
  lib-db-data:
